### ISSUE TITLE
Can genice2 generate top file of gromacs? many thanks!

### ISSUE THREAD

**Issue by mz121** [vitroid/GenIce#18]

**Comment by vitroid** [comment]
GenIce has geometry information of water molecules internally, but it is imprecise to use it as is in the .top file, and there is no information about interactions, constraints, etc.

On the other hand, it might be useful to give the top file to GenIce so that it can generate atomic configurations using it.

**Comment by mz121** [comment]
Many thanks. Can genice2 generate stacking disordered ice?

**Comment by vitroid** [comment]
Sorry for very late reply. Stacking-disordered ice 1h is implemented as "one". 

The command `genice2 one[hhccc]` generates a stacked structure of two hexagonal and three cubic ice layers.
