### ISSUE TITLE
Is it possible to add the generation of ice XIV in GenIce2?

### ISSUE THREAD

**Issue by liangwh534** [vitroid/GenIce#19]
I‘m using GenIce2 to generate structure files for a series of ice, and it has been very helpful for my work. Now I also need to generate structures for ice XIV. Could support for ice XIV be added to GenIce2?

Many thanks to this useful tool!

**Comment by vitroid** [comment]
I do not know the structure of ice XIV in detail, but it is said to be partially (dis)ordered ice.

It is possible to generate a large number of configurations using GenIce, with the hydrogen bond orientations fixed in advance for hydrogen bonds whose orientations are 100% certain, and other hydrogen bond orientations chosen completely at random.

In the reality, the orientations of the latter hydrogen bonds should also be biased, and by selecting low energy configurations from among the configurations generated by GenIce, it would be possible to create a biased configuration that is closer to the reality.

GenIce itself does not have a mechanism to evaluate energy, so the selection is up to you.

**Comment by liangwh534** [comment]
Thanks for your reply! Ice XIV is actually an ordered form of ice XII, generating this specific structure may be easier to implement in the program. But I'm still unsure how to fix the direction of hydrogen bonds. What parameter should I input in GenIce?

By the way, Here is some reference for ice XII and ice XIV.
https://water.lsbu.ac.uk/water/ice_xii.html
https://water.lsbu.ac.uk/water/ice_xiv.html

**Comment by vitroid** [comment]
Sorry for very late reply.

Now I added a new branch named "[partial-order](https://github.com/vitroid/GenIce/tree/partial-order)", in which ice 14 is implemented. It will be merged to the main after several tests.
